name: Lunes Auto Keepalive (KeepaliveSweet-Node6-US-Cookie-Based)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *" # 每天6时一次

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      LUNES_COOKIE: ${{ secrets.LUNES_COOKIE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run keepalive script
        run: npm run keepalive
