name: Lunes Auto Login

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *" # 每天凌晨 1 点 UTC 执行

jobs:
  auto-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm ci
          npx playwright install --with-deps chromium

      - name: Run Auto Login
        env:
          LUNES_USERNAME: ${{ secrets.LUNES_USERNAME }}
          LUNES_PASSWORD: ${{ secrets.LUNES_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: npm start
