name: Lunes Auto KeepAlive (KeepaliveSweet-Node6-US-Cookie-Based)

on:
  workflow_dispatch:
  schedule:
    # 每天北京时间 06:00 (UTC+8) -> UTC 22:00
    - cron: "0 22 * * *"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      LUNES_COOKIES: ${{ secrets.LUNES_COOKIES }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run keepalive script
        run: npm run keepalive
