name: BetaDash Auto Login

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # 每6小时执行一次

jobs:
  auto-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps chromium

      - name: Run auto login script
        env:
          LUNES_USERNAME: ${{ secrets.LUNES_USERNAME }}
          LUNES_PASSWORD: ${{ secrets.LUNES_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          node scripts/login.js
