
name: Auto Login & Telegram Report(keepalive-Sweet-Node6-US)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # 每 6 小时运行一次

jobs:
  auto-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install puppeteer node-fetch form-data

      - name: Run Auto Login Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        run: |
          node scripts/login.js
